// GENERATED by tools/gen-cold-table-probes.ps1 — do not hand-edit; regenerate instead.
//
// TASK-296 — distinct entity types for the cold-table storm, ported from the SQLite suite so the same
// concurrency shape can be pointed at this provider. Fewer than SQLite's 200 on purpose: the question
// here is whether the CLASS of defect exists at all on a server whose catalogue visibility is
// transactional and server-side, not to characterise its rate.
//
// Fixed-width names, so no name is a proper substring of another and TASK-293's discriminator cannot
// contaminate the result.
#nullable enable

using Birko.Data.Models;
using Birko.Data.SQL.Attributes;

namespace Birko.Data.SQL.PostgreSQL.Tests;

[Table("PgProbe00")] public class PgProbe00 : AbstractDatabaseModel { public string? Value { get; set; } }
[Table("PgProbe01")] public class PgProbe01 : AbstractDatabaseModel { public string? Value { get; set; } }
[Table("PgProbe02")] public class PgProbe02 : AbstractDatabaseModel { public string? Value { get; set; } }
[Table("PgProbe03")] public class PgProbe03 : AbstractDatabaseModel { public string? Value { get; set; } }
[Table("PgProbe04")] public class PgProbe04 : AbstractDatabaseModel { public string? Value { get; set; } }
[Table("PgProbe05")] public class PgProbe05 : AbstractDatabaseModel { public string? Value { get; set; } }
[Table("PgProbe06")] public class PgProbe06 : AbstractDatabaseModel { public string? Value { get; set; } }
[Table("PgProbe07")] public class PgProbe07 : AbstractDatabaseModel { public string? Value { get; set; } }
[Table("PgProbe08")] public class PgProbe08 : AbstractDatabaseModel { public string? Value { get; set; } }
[Table("PgProbe09")] public class PgProbe09 : AbstractDatabaseModel { public string? Value { get; set; } }
[Table("PgProbe10")] public class PgProbe10 : AbstractDatabaseModel { public string? Value { get; set; } }
[Table("PgProbe11")] public class PgProbe11 : AbstractDatabaseModel { public string? Value { get; set; } }
[Table("PgProbe12")] public class PgProbe12 : AbstractDatabaseModel { public string? Value { get; set; } }
[Table("PgProbe13")] public class PgProbe13 : AbstractDatabaseModel { public string? Value { get; set; } }
[Table("PgProbe14")] public class PgProbe14 : AbstractDatabaseModel { public string? Value { get; set; } }
[Table("PgProbe15")] public class PgProbe15 : AbstractDatabaseModel { public string? Value { get; set; } }
[Table("PgProbe16")] public class PgProbe16 : AbstractDatabaseModel { public string? Value { get; set; } }
[Table("PgProbe17")] public class PgProbe17 : AbstractDatabaseModel { public string? Value { get; set; } }
[Table("PgProbe18")] public class PgProbe18 : AbstractDatabaseModel { public string? Value { get; set; } }
[Table("PgProbe19")] public class PgProbe19 : AbstractDatabaseModel { public string? Value { get; set; } }
[Table("PgProbe20")] public class PgProbe20 : AbstractDatabaseModel { public string? Value { get; set; } }
[Table("PgProbe21")] public class PgProbe21 : AbstractDatabaseModel { public string? Value { get; set; } }
[Table("PgProbe22")] public class PgProbe22 : AbstractDatabaseModel { public string? Value { get; set; } }
[Table("PgProbe23")] public class PgProbe23 : AbstractDatabaseModel { public string? Value { get; set; } }
[Table("PgProbe24")] public class PgProbe24 : AbstractDatabaseModel { public string? Value { get; set; } }
[Table("PgProbe25")] public class PgProbe25 : AbstractDatabaseModel { public string? Value { get; set; } }
[Table("PgProbe26")] public class PgProbe26 : AbstractDatabaseModel { public string? Value { get; set; } }
[Table("PgProbe27")] public class PgProbe27 : AbstractDatabaseModel { public string? Value { get; set; } }
[Table("PgProbe28")] public class PgProbe28 : AbstractDatabaseModel { public string? Value { get; set; } }
[Table("PgProbe29")] public class PgProbe29 : AbstractDatabaseModel { public string? Value { get; set; } }
[Table("PgProbe30")] public class PgProbe30 : AbstractDatabaseModel { public string? Value { get; set; } }
[Table("PgProbe31")] public class PgProbe31 : AbstractDatabaseModel { public string? Value { get; set; } }
[Table("PgProbe32")] public class PgProbe32 : AbstractDatabaseModel { public string? Value { get; set; } }
[Table("PgProbe33")] public class PgProbe33 : AbstractDatabaseModel { public string? Value { get; set; } }
[Table("PgProbe34")] public class PgProbe34 : AbstractDatabaseModel { public string? Value { get; set; } }
[Table("PgProbe35")] public class PgProbe35 : AbstractDatabaseModel { public string? Value { get; set; } }
[Table("PgProbe36")] public class PgProbe36 : AbstractDatabaseModel { public string? Value { get; set; } }
[Table("PgProbe37")] public class PgProbe37 : AbstractDatabaseModel { public string? Value { get; set; } }
[Table("PgProbe38")] public class PgProbe38 : AbstractDatabaseModel { public string? Value { get; set; } }
[Table("PgProbe39")] public class PgProbe39 : AbstractDatabaseModel { public string? Value { get; set; } }
[Table("PgProbe40")] public class PgProbe40 : AbstractDatabaseModel { public string? Value { get; set; } }
[Table("PgProbe41")] public class PgProbe41 : AbstractDatabaseModel { public string? Value { get; set; } }
[Table("PgProbe42")] public class PgProbe42 : AbstractDatabaseModel { public string? Value { get; set; } }
[Table("PgProbe43")] public class PgProbe43 : AbstractDatabaseModel { public string? Value { get; set; } }
[Table("PgProbe44")] public class PgProbe44 : AbstractDatabaseModel { public string? Value { get; set; } }
[Table("PgProbe45")] public class PgProbe45 : AbstractDatabaseModel { public string? Value { get; set; } }
[Table("PgProbe46")] public class PgProbe46 : AbstractDatabaseModel { public string? Value { get; set; } }
[Table("PgProbe47")] public class PgProbe47 : AbstractDatabaseModel { public string? Value { get; set; } }
[Table("PgProbe48")] public class PgProbe48 : AbstractDatabaseModel { public string? Value { get; set; } }
[Table("PgProbe49")] public class PgProbe49 : AbstractDatabaseModel { public string? Value { get; set; } }
[Table("PgProbe50")] public class PgProbe50 : AbstractDatabaseModel { public string? Value { get; set; } }
[Table("PgProbe51")] public class PgProbe51 : AbstractDatabaseModel { public string? Value { get; set; } }
[Table("PgProbe52")] public class PgProbe52 : AbstractDatabaseModel { public string? Value { get; set; } }
[Table("PgProbe53")] public class PgProbe53 : AbstractDatabaseModel { public string? Value { get; set; } }
[Table("PgProbe54")] public class PgProbe54 : AbstractDatabaseModel { public string? Value { get; set; } }
[Table("PgProbe55")] public class PgProbe55 : AbstractDatabaseModel { public string? Value { get; set; } }
[Table("PgProbe56")] public class PgProbe56 : AbstractDatabaseModel { public string? Value { get; set; } }
[Table("PgProbe57")] public class PgProbe57 : AbstractDatabaseModel { public string? Value { get; set; } }
[Table("PgProbe58")] public class PgProbe58 : AbstractDatabaseModel { public string? Value { get; set; } }
[Table("PgProbe59")] public class PgProbe59 : AbstractDatabaseModel { public string? Value { get; set; } }

public static class PgColdTableProbes
{
    public static readonly System.Type[] All = new System.Type[]
    {
        typeof(PgProbe00),
        typeof(PgProbe01),
        typeof(PgProbe02),
        typeof(PgProbe03),
        typeof(PgProbe04),
        typeof(PgProbe05),
        typeof(PgProbe06),
        typeof(PgProbe07),
        typeof(PgProbe08),
        typeof(PgProbe09),
        typeof(PgProbe10),
        typeof(PgProbe11),
        typeof(PgProbe12),
        typeof(PgProbe13),
        typeof(PgProbe14),
        typeof(PgProbe15),
        typeof(PgProbe16),
        typeof(PgProbe17),
        typeof(PgProbe18),
        typeof(PgProbe19),
        typeof(PgProbe20),
        typeof(PgProbe21),
        typeof(PgProbe22),
        typeof(PgProbe23),
        typeof(PgProbe24),
        typeof(PgProbe25),
        typeof(PgProbe26),
        typeof(PgProbe27),
        typeof(PgProbe28),
        typeof(PgProbe29),
        typeof(PgProbe30),
        typeof(PgProbe31),
        typeof(PgProbe32),
        typeof(PgProbe33),
        typeof(PgProbe34),
        typeof(PgProbe35),
        typeof(PgProbe36),
        typeof(PgProbe37),
        typeof(PgProbe38),
        typeof(PgProbe39),
        typeof(PgProbe40),
        typeof(PgProbe41),
        typeof(PgProbe42),
        typeof(PgProbe43),
        typeof(PgProbe44),
        typeof(PgProbe45),
        typeof(PgProbe46),
        typeof(PgProbe47),
        typeof(PgProbe48),
        typeof(PgProbe49),
        typeof(PgProbe50),
        typeof(PgProbe51),
        typeof(PgProbe52),
        typeof(PgProbe53),
        typeof(PgProbe54),
        typeof(PgProbe55),
        typeof(PgProbe56),
        typeof(PgProbe57),
        typeof(PgProbe58),
        typeof(PgProbe59),
    };
}
